export const SET_MAX = "SET_MAX";
export const GET_MAX = "GET_MAX";

/* Journal Actions */
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const FETCH_JOURNAL = "FETCH_JOURNAL";
export const RECEIVE_JOURNAL_SUCCESS = "RECEIVE_JOURNAL_SUCCESS";
export const RECEIVE_JOURNAL_EMPTY = "RECEIVE_JOURNAL_EMPTY";
export const RECEIVE_JOURNAL_FAILURE = "RECEIVE_JOURNAL_FAILURE";

export const UPDATE_NUTRITION = "UPDATE_NUTRITION";
export const SET_WATER_INTAKE = "SET_WATER_INTAKE";
export const UPDATE_WATER_INTAKE = "UPDATE_WATER_INTAKE";
export const ADD_EXERCISE = "ADD_EXERCISE";

/* User Actions */
export const FETCH_MEALS = "FETCH_MEALS";
export const SET_USER = "SET_USER";
export const SET_MEALS = "SET_MEALS";
export const SET_USERNAME = "SET_USERNAME";